# #####################################################################
# Automatically generated by qmake (2.01a) mer. dc. 7 20:26:03 2011
# #####################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = rechercher
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h \
    mainwindow.h
SOURCES += finddialog.cpp \
    main.cpp \
    mainwindow.cpp
